### ISSUE TITLE
Giphy http version

### ISSUE THREAD

**Issue by AIBuilderExpert** [brianegan/giphy_client#4]
Because every version of giphy_client depends on http ^0.11.3+16 and stripe_api 1.1.0 depends on http ^0.12.0, giphy_client is incompatible with stripe_api 1.1.0.
And because no versions of stripe_api match >1.1.0 <2.0.0, giphy_client is incompatible with stripe_api ^1.1.0.
So, because gyfted_app depends on both stripe_api ^1.1.0 and giphy_client ^0.0.1, version solving failed.

**Comment by CosmicPangolin** [comment]
@brianegan Similar but on json_annotation.  Happy to fork, but would love to see dependencies upgraded so this package remains relevant.  Would a PR help?

**Comment by brianegan** [comment]
Oh dang, sorry I missed this one! Yep, a PR would be much appreciated compared to a complete fork :)

**Comment by brianegan** [comment]
Jk -- found 30 minutes in the day and fixed this up. Uploaded a new version 0.2.0 with fixes :)

**Comment by CosmicPangolin** [comment]
<3
